In [ ]:
import pandas as pd

In [ ]:

df = pd.read_csv("Iris.csv")

In [ ]:
iris = pd.read_csv("Iris.csv", header = None)

In [ ]:
col_names =['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width','Species']

In [ ]:
iris = pd.read_csv("Iris.csv", names = col_names)

In [ ]:
df1=df=iris

In [ ]:
iris.head(8)

     Sepal_Length   Sepal_Width   Petal_Length   Petal_Width      Species
Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa
6             5.4           3.9            1.7           0.4  Iris-setosa
7             4.6           3.4            1.4           0.3  Iris-setosa

In [ ]:

iris.tail()

    Sepal_Length Sepal_Width Petal_Length Petal_Width         Species
146          6.7         3.0          5.2         2.3  Iris-virginica
147          6.3         2.5          5.0         1.9  Iris-virginica
148          6.5         3.0          5.2         2.0  Iris-virginica
149          6.2         3.4          5.4         2.3  Iris-virginica
150          5.9         3.0          5.1         1.8  Iris-virginica

In [ ]:
iris.index

Index(['Id', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '141', '142', '143', '144', '145', '146', '147', '148', '149', '150'],
      dtype='object', length=151)

In [ ]:
iris.columns

Index(['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width',
       'Species'],
      dtype='object')

In [ ]:
iris.shape

(151, 5)

In [ ]:
iris.dtypes

Sepal_Length    object
Sepal_Width     object
Petal_Length    object
Petal_Width     object
Species         object
dtype: object

In [ ]:
iris.describe()

       Sepal_Length Sepal_Width Petal_Length Petal_Width      Species
count           151         151          151         151          151
unique           36          24           44          23            4
top             5.0         3.0          1.5         0.2  Iris-setosa
freq             10          26           14          28           50

In [ ]:
iris.columns.values

array(['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width',
       'Species'], dtype=object)

In [ ]:
iris.iloc[5]

Sepal_Length            5.0
Sepal_Width             3.6
Petal_Length            1.4
Petal_Width             0.2
Species         Iris-setosa
Name: 5, dtype: object

In [ ]:
iris[47:51]

   Sepal_Length Sepal_Width Petal_Length Petal_Width      Species
47          5.1         3.8          1.6         0.2  Iris-setosa
48          4.6         3.2          1.4         0.2  Iris-setosa
49          5.3         3.7          1.5         0.2  Iris-setosa
50          5.0         3.3          1.4         0.2  Iris-setosa

In [ ]:
iris.loc[:,["Sepal_Length","Sepal_Width"]]

      Sepal_Length   Sepal_Width
Id   SepalLengthCm  SepalWidthCm
1              5.1           3.5
2              4.9           3.0
3              4.7           3.2
4              4.6           3.1
..             ...           ...
146            6.7           3.0
147            6.3           2.5
148            6.5           3.0
149            6.2           3.4
150            5.9           3.0

[151 rows x 2 columns]

In [ ]:
cols_2_4=iris.columns[2:4]
iris[cols_2_4]

      Petal_Length   Petal_Width
Id   PetalLengthCm  PetalWidthCm
1              1.4           0.2
2              1.4           0.2
3              1.3           0.2
4              1.5           0.2
..             ...           ...
146            5.2           2.3
147            5.0           1.9
148            5.2           2.0
149            5.4           2.3
150            5.1           1.8

[151 rows x 2 columns]

In [ ]:
iris.isnull().any()

Sepal_Length    False
Sepal_Width     False
Petal_Length    False
Petal_Width     False
Species         False
dtype: bool

In [ ]:
iris.isnull().sum()

Sepal_Length    0
Sepal_Width     0
Petal_Length    0
Petal_Width     0
Species         0
dtype: int64

In [ ]:
iris.dtypes

Sepal_Length    object
Sepal_Width     object
Petal_Length    object
Petal_Width     object
Species         object
dtype: object

In [ ]:
import pandas as pd

df = iris 
df['Petal_Length'] = pd.to_numeric(df['Petal_Length'], errors='coerce')
df['Petal_Length'] = df['Petal_Length'].fillna(df['Petal_Length'].mean())
df['Petal_Length'] = df['Petal_Length'].astype(int)
print(df.head())

     Sepal_Length   Sepal_Width  Petal_Length   Petal_Width      Species
Id  SepalLengthCm  SepalWidthCm             3  PetalWidthCm      Species
1             5.1           3.5             1           0.2  Iris-setosa
2             4.9           3.0             1           0.2  Iris-setosa
3             4.7           3.2             1           0.2  Iris-setosa
4             4.6           3.1             1           0.2  Iris-setosa

In [ ]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()

In [ ]:
X=iris.iloc[:,:4]

In [ ]:
x = 10
print(x)

10

In [ ]:
from sklearn.preprocessing import MinMaxScaler

X_numeric = X.select_dtypes(include=['number'])

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_numeric)

import pandas as pd
X_scaled = pd.DataFrame(X_scaled, columns=X_numeric.columns)
print(X_scaled.head())

   Petal_Length
0           0.4
1           0.0
2           0.0
3           0.0
4           0.0

In [ ]:
df_normalized = pd.DataFrame(X_scaled)

In [ ]:
df_normalized

     Petal_Length
0             0.4
1             0.0
2             0.0
3             0.0
4             0.0
..            ...
146           0.8
147           0.8
148           0.8
149           0.8
150           0.8

[151 rows x 1 columns]

In [ ]:
df2=df
df2['Species'].unique()

array(['Species', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica'],
      dtype=object)

In [ ]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()

In [ ]:
features_df=df2.drop(columns=['Species'])

In [ ]:

features_df

      Sepal_Length   Sepal_Width  Petal_Length   Petal_Width
Id   SepalLengthCm  SepalWidthCm             3  PetalWidthCm
1              5.1           3.5             1           0.2
2              4.9           3.0             1           0.2
3              4.7           3.2             1           0.2
4              4.6           3.1             1           0.2
..             ...           ...           ...           ...
146            6.7           3.0             5           2.3
147            6.3           2.5             5           1.9
148            6.5           3.0             5           2.0
149            6.2           3.4             5           2.3
150            5.9           3.0             5           1.8

[151 rows x 4 columns]

In [ ]:
enc_df=(enc.fit_transform(df2[['Species']])).toarray()

In [ ]:
import pandas as pd

enc_df = pd.DataFrame(enc_df)  
enc_df = enc_df.iloc[:, :3]  
enc_df.columns = ['Iris-Setosa', 'Iris-Versicolor', 'Iris-Virginica']

In [ ]:
df_encode = features_df.join(enc_df)

In [ ]:
df_encode

,Sepal_Length,Sepal_Width,Petal_Length,Petal_Width,Iris-Setosa,Iris-Versicolor,Iris-Virginica
Id,SepalLengthCm,SepalWidthCm,3,PetalWidthCm,NaN,NaN,NaN
1,5.1,3.5,1,0.2,NaN,NaN,NaN
2,4.9,3.0,1,0.2,NaN,NaN,NaN
3,4.7,3.2,1,0.2,NaN,NaN,NaN
4,4.6,3.1,1,0.2,NaN,NaN,NaN
...,...,...,...,...,...,...,...
146,6.7,3.0,5,2.3,NaN,NaN,NaN
147,6.3,2.5,5,1.9,NaN,NaN,NaN
148,6.5,3.0,5,2.0,NaN,NaN,NaN
149,6.2,3.4,5,2.3,NaN,NaN,NaN
150,5.9,3.0,5,1.8,NaN,NaN,NaN